"""Add position restake count field

Revision ID: 05f17c77dd4d
Revises: 17810e991dcc
Create Date: 2022-03-30 13:43:51.622897

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "05f17c77dd4d"
down_revision = "17810e991dcc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("staking_positions", sa.Column("restake_count", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("staking_positions", "restake_count")
    # ### end Alembic commands ###
