"""Add protocol TVL

Revision ID: 266a0dc816d5
Revises: 09eccbf364b9
Create Date: 2022-05-06 07:36:11.864694

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "266a0dc816d5"
down_revision = "09eccbf364b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("protocols", sa.Column("tvl", sa.NUMERIC(precision=78), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("protocols", "tvl")
    # ### end Alembic commands ###
