"""Add block field to StakingPositions

Revision ID: 3e7edd31ec8a
Revises: 469a8a106c2f
Create Date: 2022-07-12 13:18:08.942815

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3e7edd31ec8a"
down_revision = "469a8a106c2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("staking_positions", sa.Column("block", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("staking_positions", "block")
    # ### end Alembic commands ###
