"""Create ProtocolCoverage model

Revision ID: 7317246bb7d8
Revises: 17810e991dcc
Create Date: 2022-03-28 17:17:26.330592

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7317246bb7d8"
down_revision = "e9513456df23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "protocols_coverages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_id", sa.Integer(), nullable=False),
        sa.Column("coverage_amount", sa.NUMERIC(precision=78), nullable=False),
        sa.Column("coverage_amount_set_at", postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["protocol_id"],
            ["protocols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("protocols_coverages")
    # ### end Alembic commands ###
