"""Create Airdrop model

Revision ID: 7b2cb6761ec4
Revises: fe1a6b4ecd8a
Create Date: 2022-08-04 17:06:12.862003

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7b2cb6761ec4"
down_revision = "fe1a6b4ecd8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airdrops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=78), nullable=False),
        sa.Column("proof", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("claimed_at_block", sa.Integer(), nullable=True),
        sa.Column("claimed_at_timestamp", postgresql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("airdrops")
    # ### end Alembic commands ###
