"""Create IntervalFunction model

Revision ID: 8961749817c1
Revises: 469a8a106c2f
Create Date: 2022-07-15 13:16:46.394841

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8961749817c1"
down_revision = "469a8a106c2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interval_functions",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("block_last_run", sa.Integer(), server_default="0", nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interval_functions")
    # ### end Alembic commands ###
