"""Add additional_apy

Revision ID: 9563fd232d2f
Revises: fe1a6b4ecd8a
Create Date: 2022-08-29 13:49:43.314919

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9563fd232d2f"
down_revision = "fe1a6b4ecd8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("indexer_state", sa.Column("additional_apy", sa.Float(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer_state", "additional_apy")
    # ### end Alembic commands ###
