"""Add claimed_at field to FundraisPosition

Revision ID: b54caacad6b6
Revises: 6d89ae0bffc6
Create Date: 2022-09-05 13:42:37.882306

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b54caacad6b6"
down_revision = "6d89ae0bffc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fundraise_positions", sa.Column("claimed_at", postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fundraise_positions", "claimed_at")
    # ### end Alembic commands ###
