"""Create ProtocolPremium model

Revision ID: e93e2e0034cb
Revises: 82db2e875c18
Create Date: 2022-03-23 11:37:16.691324

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e93e2e0034cb"
down_revision = "82db2e875c18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "protocols_premiums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_id", sa.Integer(), nullable=False),
        sa.Column("premium", sa.NUMERIC(precision=78), nullable=False),
        sa.Column("premium_set_at", postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["protocol_id"],
            ["protocols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("protocols_premiums")
    # ### end Alembic commands ###
