"""Create ProtocolsNonstakers table

Revision ID: ed8fd7dd2dcb
Revises: b54caacad6b6
Create Date: 2024-05-22 23:13:34.917434

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed8fd7dd2dcb"
down_revision = "b54caacad6b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "protocols_nonstakers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_id", sa.Integer(), nullable=False),
        sa.Column("nonstakers", sa.NUMERIC(precision=78), nullable=False),
        sa.Column("nonstakers_set_at", postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["protocol_id"],
            ["protocols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("protocols_nonstakers")
    # ### end Alembic commands ###
