"""Add premiums_apy field to IndexerState

Revision ID: fe1a6b4ecd8a
Revises: 8961749817c1
Create Date: 2022-07-15 14:55:51.766995

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fe1a6b4ecd8a"
down_revision = "8961749817c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("indexer_state", sa.Column("premiums_apy", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer_state", "premiums_apy")
    # ### end Alembic commands ###
