"""Initial version

Revision ID: fe37d8daf410
Revises:
Create Date: 2022-03-22 16:47:45.309197

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fe37d8daf410"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fundraise_positions",
        sa.Column("id", sa.String(length=42), nullable=False),
        sa.Column("stake", sa.NUMERIC(precision=78), nullable=False),
        sa.Column("contribution", sa.NUMERIC(precision=78), nullable=False),
        sa.Column("reward", sa.NUMERIC(precision=78), nullable=False),
        sa.Column("claimable_at", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "indexer_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_block", sa.Integer(), nullable=False),
        sa.Column("last_time", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("balance_factor", sa.NUMERIC(precision=78, scale=70), nullable=False),
        sa.Column("apy", sa.Float(), nullable=False),
        sa.Column("apy_50ms_factor", sa.NUMERIC(precision=78, scale=70), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "staking_positions",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("owner", sa.String(length=42), nullable=False),
        sa.Column("lockup_end", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("usdc", sa.NUMERIC(precision=78), nullable=False),
        sa.Column("sher", sa.NUMERIC(precision=78), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "staking_positions_meta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usdc_last_updated", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("usdc_last_updated_block", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("staking_positions_meta")
    op.drop_table("staking_positions")
    op.drop_table("indexer_state")
    op.drop_table("fundraise_positions")
    # ### end Alembic commands ###
